In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

print("pytorch version : {}".format(torch.__version__))

pytorch version : 1.3.0


# 1. List
### 1-1. convert ***list*** to ***torch tensor***

In [2]:
x = [[1, 2, 3], [4, 5, 6]]
print("x type : ", type(x))
print(x)

x type :  <class 'list'>
[[1, 2, 3], [4, 5, 6]]


In [3]:
# x_tensor = torch.FloatTensor(x) #dtype : float32
# x_tensor = torch.Tensor(x) #dtype : float32
x_tensor = torch.IntTensor(x) #dtype : int32
print(x_tensor)
print(x_tensor.size())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
torch.Size([2, 3])


### 1-2. Create a float32 tensor of shape(3, 2), filled with 3

In [4]:
x = torch.FloatTensor(3, 2).fill_(10)
print(x)
print(x.dtype)

tensor([[10., 10.],
        [10., 10.],
        [10., 10.]])
torch.float32


### 1-3. Convert ***Tensor*** to ***List***

In [5]:
x_tensor = torch.randn (3, 3)
print(x_tensor)
print(x_tensor.size())
print(x_tensor.dtype)

tensor([[ 1.7235,  1.0856, -0.3898],
        [-2.2680, -0.4158, -1.0240],
        [ 0.9287, -0.4326, -1.6315]])
torch.Size([3, 3])
torch.float32


In [6]:
print("\n=======convert tensor to list========\n")

x_list = x_tensor.tolist()

print(x_list)
print(type(x_list))
print(len(x_list))


=======convert tensor to list========

[[1.723530650138855, 1.0855711698532104, -0.38979217410087585], [-2.26798415184021, -0.4157618582248688, -1.0239917039871216], [0.9287456274032593, -0.43257948756217957, -1.6314820051193237]]
<class 'list'>
3


# Numpy

### 2-1. Convert ***Numpy array*** to ***torch tensor***

In [7]:
x_numpy = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(x_numpy)
print(x_numpy.shape)

print("\n=====Convert Numpy to tensor======\n")

x_tensor = torch.from_numpy(x_numpy)
print(x_tensor)
print(x_tensor.dtype)
print(x_tensor.size())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

=====Convert Numpy to tensor======

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64
torch.Size([3, 3])


### 2-2. Convert ***Tensor*** to ***Numpy***

In [8]:
x_tensor = torch.randn(3, 3)
print(x_tensor)
print(x_tensor.size())

print("\n=====Convert torch to Numpy=====\n")

x_numpy = x_tensor.numpy()
print(x_numpy)
print(x_numpy.shape)
print(type(x_numpy))

tensor([[ 0.1383, -1.7878, -2.0272],
        [ 0.8119,  0.9957, -1.7770],
        [-0.1743, -0.0082, -1.0029]])
torch.Size([3, 3])

=====Convert torch to Numpy=====

[[ 0.13833393 -1.7877554  -2.0271626 ]
 [ 0.81189215  0.99566746 -1.7770418 ]
 [-0.17429647 -0.00817963 -1.0028696 ]]
(3, 3)
<class 'numpy.ndarray'>


# 3. Filled ones and zeros

### 3-1. Create a 3-by3 2D Tensor with ones on the diagonal and zeros elsewhere

In [9]:
x_tensor = torch.eye(3)
print(x_tensor)
print(x_tensor.size())

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([3, 3])


### 3-2. Create a tensor with shape a (3, 2) filled with 1

In [10]:
x_tensor = torch.FloatTensor(3, 2).fill_(1)
#x_tensor = torch.ones(3, 2)
print(x_tensor)
print(x_tensor.dtype)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
torch.float32


### 3-3. Create a tensor with shape a (3, 2) filled with 0

In [11]:
x_tensor = torch.zeros(3, 2)
#x_tensor = torch.FloatTensor(3, 2).fill_(0)
print(x_tensor)
print(x_tensor.dtype)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
torch.float32
