In [1]:
import torch
import numpy as np

print(torch.__version__)

1.3.0


# 1. Size and Resize

### 1-1. Get the size and type of 'x'

- torch.tensor는 numpy 와 비슷하게 사용이 가능하지만, shape을 확인할땐 ***size()***로 확인을 해야한다.

In [2]:
x = torch.randn(3, 2, 1) # (3, 2, 1) shape을 갖고 랜덤값으로 채워준다.
y = x.size() # torch.tensor인 x의 size를 확인한다

print("torch tensor size : {}".format(y))
print("torch tensor type : {}".format(x.type()))

assert y==x.numpy().shape

torch tensor size : torch.Size([3, 2, 1])
torch tensor type : torch.FloatTensor


### 1-2. Get the total number of elements in x
- .numel() : torch.tensor 값들의 총 합을 구하는 함수

In [3]:
x = torch.randn(3, 2, 2) #기본적으노 Float tensor로 setting이 된다.
print(x.type())
y = x.numel() # (3, 2, 2) 차원을 갖는 x의 원소 합을 구하는 함수

print(x)
print(y)

torch.FloatTensor
tensor([[[ 0.0729,  0.0468],
         [ 0.7216, -0.3420]],

        [[-1.4557, -1.4376],
         [ 0.3464,  1.7269]],

        [[ 1.2108, -0.4587],
         [-1.5447, -1.2787]]])
12


### 1-3. Get the number of dimensions of x

- Tensorflow and Keras shape : (H, W, C)
- Pytorch shape : (C, H, W)

In [4]:
x = torch.randn(3, 2, 1)
print("x의 차원 : ", x.dim())
print(x.size())

x의 차원 :  3
torch.Size([3, 2, 1])


### 1-4. Resize x to shape of (10, 3)

torch로 shape을 변경해가며 model에 넣어줄때, shape을 변경해야할 경우가 생기게 된다. 이때, 전체 함이 값은 값이 나온다는 전재하네 shape을 변경할 수 있다.

In [5]:
x = torch.randn(5, 6)
print(x.size())
print(x)

print("\n=====Resize=====\n")

x_resize = x.resize(10, 3)
print(x_resize.size())
print(x_resize)

torch.Size([5, 6])
tensor([[ 0.8541, -0.3166,  0.6494, -0.3390, -1.4015,  0.7518],
        [-0.5903,  0.0742,  0.8404,  0.3509,  0.2091,  0.7638],
        [ 1.4224, -0.7578, -0.6472, -1.1049,  0.8404,  0.8299],
        [ 1.6354, -0.8514, -0.3302,  0.1855, -0.7958, -1.4168],
        [ 0.3381,  0.4326, -0.2390, -0.7901,  0.3790,  0.6520]])

=====Resize=====

torch.Size([10, 3])
tensor([[ 0.8541, -0.3166,  0.6494],
        [-0.3390, -1.4015,  0.7518],
        [-0.5903,  0.0742,  0.8404],
        [ 0.3509,  0.2091,  0.7638],
        [ 1.4224, -0.7578, -0.6472],
        [-1.1049,  0.8404,  0.8299],
        [ 1.6354, -0.8514, -0.3302],
        [ 0.1855, -0.7958, -1.4168],
        [ 0.3381,  0.4326, -0.2390],
        [-0.7901,  0.3790,  0.6520]])


/Users/kojaeyeong/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/tensor.py:314: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


### 1-5. Remove all the dimensions of size 1 in x

- squeeze() : 1값을 갖는 차원을 제거해주는 방법이다.

In [6]:
x = torch.randn(10, 6, 1, 1)
print(x.size())

y = x.squeeze()
print(y.size())

torch.Size([10, 6, 1, 1])
torch.Size([10, 6])


### 1-6. Remove only the thrid dimenstion in x

In [7]:
x = torch.randn(10, 6, 1, 3)
y = x.squeeze(2)
print(y.size())

torch.Size([10, 6, 3])


### 1-7. Remove only the last dimenstion in x

In [8]:
x = torch.randn(10, 6, 1, 3, 1)
print(x.size())
y = x.squeeze(-1)
print(y.size())

torch.Size([10, 6, 1, 3, 1])
torch.Size([10, 6, 1, 3])


### 1-8.Add a dimenstion of 1 at the end

In [9]:
x  = torch.ones(10, 10, 3)
print(x.size())
y = x.unsqueeze(-1)
print(y.size())

torch.Size([10, 10, 3])
torch.Size([10, 10, 3, 1])


### 1-9. Convert 1 dim to 3 dim (using the ***np.concatenate***)

In [10]:
x = torch.randn(10, 10, 1)
x_numpy = x.numpy()
print(x_numpy.shape)

x_concat = np.concatenate((x_numpy, np.concatenate((x_numpy, x_numpy), axis=-1)), axis=-1)
print(x_concat.shape)
x_tensor = torch.from_numpy(x_concat)
print(x_tensor.size())

(10, 10, 1)
(10, 10, 3)
torch.Size([10, 10, 3])


# 2. Indexing, Slicing, Joining, Mutating ops

### 2-1. Resize를 해주고 indexing 해주기

In [11]:
x = torch.arange(1, 22)
print(x.size())
print(x)

print("\n====== Resize ======\n")

x_resize = x.resize(3, 7)
print(x_resize.size())
print(x_resize)

print("\n====== indexing ======\n")
y = torch.LongTensor([0, 2, 4, 5])
print(y)
print("\n[indexing] \n{}".format(x_resize.index_select(1, y)))

torch.Size([21])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21])

====== Resize ======

torch.Size([3, 7])
tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21]])

====== indexing ======

tensor([0, 2, 4, 5])

[indexing] 
tensor([[ 1,  3,  5,  6],
        [ 8, 10, 12, 13],
        [15, 17, 19, 20]])


### 2-2. Mask 씌워주기

In [12]:
x = torch.arange(1, 11)
print(x)
mask = x.gt(4) # 4번째 index 부터는 True로(1) 그 이하는 False(0)으로 채우기
print(mask)
print(x.masked_select(mask))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([False, False, False, False,  True,  True,  True,  True,  True,  True])
tensor([ 5,  6,  7,  8,  9, 10])


### 2-3. 2차원 크기를 동일한 크기로 tensor를 split

In [13]:
x = torch.arange(1, 11).resize(2, 5)
print(x.size())
print(x)

print("\n===== split tensor =====\n")

y_chunk = x.chunk(5)
print(y_chunk)
print(type(y_chunk))

tensor1, tensor2 = y_chunk
print("tensor1 : {}, tensor2 : {}".format(tensor1, tensor2))

torch.Size([2, 5])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

===== split tensor =====

(tensor([[1, 2, 3, 4, 5]]), tensor([[ 6,  7,  8,  9, 10]]))
<class 'tuple'>
tensor1 : tensor([[1, 2, 3, 4, 5]]), tensor2 : tensor([[ 6,  7,  8,  9, 10]])


In [14]:
x = torch.arange(1, 11).resize(2, 5)
print(x)

y_split = torch.unbind(x, axis=1)
print(type(y_split))
print(y_split)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
<class 'tuple'>
(tensor([1, 6]), tensor([2, 7]), tensor([3, 8]), tensor([4, 9]), tensor([ 5, 10]))


### 2-4. Stack x, y and z vertically.

In [15]:
x = torch.IntTensor([1, 4])
y = torch.IntTensor([2, 5])
z = torch.IntTensor([3, 6])

tensor_stack = torch.stack((x, y,z), dim=0)
print(tensor_stack)
print(tensor_stack.size())

tensor([[1, 4],
        [2, 5],
        [3, 6]], dtype=torch.int32)
torch.Size([3, 2])


### 2-5. Concatenate X and Y along the first dimenstion

In [16]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.FloatTensor([[7, 8, 9], [10, 11, 12]])
z = torch.cat((x, y), dim=0)
#z = torch.stack((x, y), dim=0) # --> (2, 2, 3) 이 되버림.
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


### 2-6. Transpose First and second dimenstion of x

In [17]:
x = torch.randn(3, 2)
print(x)
print(x.size())
print("\n=====Transpos=====\n")
y = x.t()
print(y)
print(y.size())

tensor([[-0.3929,  1.6695],
        [ 0.1826,  0.9148],
        [-0.5228, -0.4459]])
torch.Size([3, 2])

=====Transpos=====

tensor([[-0.3929,  0.1826, -0.5228],
        [ 1.6695,  0.9148, -0.4459]])
torch.Size([2, 3])


### 2-7. *Dimenstion 순서 변경하기*

In [18]:
x = torch.ones(1, 2, 3)
print(x.size())
y = x.permute(2, 0, 1)
print(y.size())

torch.Size([1, 2, 3])
torch.Size([3, 1, 2])


# 3. Sorting

In [19]:
x = torch.Tensor([[1, 4], [3, 1]])
print(x)
print(x.size())

sorted_tensor, sorted_indices = x.sort(1)
print("sorted tensor : ", sorted_tensor)
print("sorted indices : ", sorted_indices)
#3과 1이 위치가 바뀌면서 정렬(sort)된걸 볼 수 있따, 그래서 index에서 위치가 변경됬다고 알려주는 것이다.

tensor([[1., 4.],
        [3., 1.]])
torch.Size([2, 2])
sorted tensor :  tensor([[1., 4.],
        [1., 3.]])
sorted indices :  tensor([[0, 1],
        [1, 0]])


# 4. Counting

### 4-1. zero가 아닌 값들의 위치를 알려줌


In [20]:
x = torch.Tensor([[0,1,7,0,0], [3,0,0,2,19]])
print(x)
print(x.size())

y = x.nonzero()
print(y) # 2차원 이다. 0행 1열, 0행 2열, 1행 0열 이 0이 아닌 값이라는걸 알려주는 것.
print(y.size())

tensor([[ 0.,  1.,  7.,  0.,  0.],
        [ 3.,  0.,  0.,  2., 19.]])
torch.Size([2, 5])
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 3],
        [1, 4]])
torch.Size([5, 2])
